version: "3"

services:
  docker:
    image: docker:dind
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
      - 3000:3000 # react-app
      - 8501:8501 # python app
    restart: always
    command: --storage-driver overlay2

  myjenkins-blueocean:
    image: myjenkins-blueocean
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    ports:
      - 49000:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - $HOME:/home
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - 9000:9000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - jenkins

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - jenkins

  grafana:
    image: grafana/grafana
    ports:
      - 3030:3030
    environment:
      - GF_SERVER_HTTP_PORT=3030
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-docker-certs:
  jenkins-data:
